param(
  [string]$OutputDirectory = (Join-Path $PSScriptRoot '..\assets\icons'),
  [string]$DataOutputPath = (Join-Path $PSScriptRoot '..\js\icon-data.js')
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

Add-Type -AssemblyName System.Drawing

$iconDefinitions = @(
  @{ Key = 'fixed';     Name = 'fixed';      Color = '#8b5cf6'; Text = 'G' }
  @{ Key = 'direct';    Name = 'direct';     Color = '#0ea5e9'; Text = 'D' }
  @{ Key = 'system';    Name = 'system';     Color = '#64748b'; Text = 'S' }
  @{ Key = 'pac_gray';  Name = 'pac-gray';   Color = '#94a3b8'; Text = 'A' }
  @{ Key = 'pac_green'; Name = 'pac-green';  Color = '#10b981'; Text = 'A' }
  @{ Key = 'pac_blue';  Name = 'pac-blue';   Color = '#0ea5e9'; Text = 'W' }
  @{ Key = 'pac_org';   Name = 'pac-orange'; Color = '#f59e0b'; Text = 'T' }
  @{ Key = 'pac_purp';  Name = 'pac-purple'; Color = '#8b5cf6'; Text = 'M' }
)

function New-RoundedRectanglePath {
  param(
    [int]$Size,
    [float]$Radius
  )

  $diameter = $Radius * 2
  $path = [System.Drawing.Drawing2D.GraphicsPath]::new()
  $path.AddArc(0, 0, $diameter, $diameter, 180, 90)
  $path.AddArc($Size - $diameter, 0, $diameter, $diameter, 270, 90)
  $path.AddArc($Size - $diameter, $Size - $diameter, $diameter, $diameter, 0, 90)
  $path.AddArc(0, $Size - $diameter, $diameter, $diameter, 90, 90)
  $path.CloseFigure()
  return $path
}

function Convert-BitmapToRgbaBase64 {
  param([System.Drawing.Bitmap]$Bitmap)

  $bytes = [byte[]]::new($Bitmap.Width * $Bitmap.Height * 4)
  $index = 0
  for ($y = 0; $y -lt $Bitmap.Height; $y++) {
    for ($x = 0; $x -lt $Bitmap.Width; $x++) {
      $pixel = $Bitmap.GetPixel($x, $y)
      $bytes[$index++] = $pixel.R
      $bytes[$index++] = $pixel.G
      $bytes[$index++] = $pixel.B
      $bytes[$index++] = $pixel.A
    }
  }

  return [Convert]::ToBase64String($bytes)
}

$resolvedOutputDirectory = [System.IO.Path]::GetFullPath($OutputDirectory)
[System.IO.Directory]::CreateDirectory($resolvedOutputDirectory) | Out-Null
$generatedIconData = [ordered]@{}

foreach ($definition in $iconDefinitions) {
  $generatedIconData[$definition.Key] = [ordered]@{}
  foreach ($size in @(16, 32)) {
    $bitmap = [System.Drawing.Bitmap]::new(
      $size,
      $size,
      [System.Drawing.Imaging.PixelFormat]::Format32bppArgb
    )
    $graphics = [System.Drawing.Graphics]::FromImage($bitmap)
    $path = New-RoundedRectanglePath -Size $size -Radius ($size / 4)
    $backgroundBrush = [System.Drawing.SolidBrush]::new(
      [System.Drawing.ColorTranslator]::FromHtml($definition.Color)
    )
    $textBrush = [System.Drawing.SolidBrush]::new([System.Drawing.Color]::White)
    $font = [System.Drawing.Font]::new(
      'Segoe UI',
      $size * 22 / 32,
      [System.Drawing.FontStyle]::Bold,
      [System.Drawing.GraphicsUnit]::Pixel
    )
    $textFormat = [System.Drawing.StringFormat]::new()

    try {
      $graphics.Clear([System.Drawing.Color]::Transparent)
      $graphics.SmoothingMode = [System.Drawing.Drawing2D.SmoothingMode]::AntiAlias
      $graphics.CompositingQuality = [System.Drawing.Drawing2D.CompositingQuality]::HighQuality
      $graphics.InterpolationMode = [System.Drawing.Drawing2D.InterpolationMode]::HighQualityBicubic
      $graphics.PixelOffsetMode = [System.Drawing.Drawing2D.PixelOffsetMode]::HighQuality
      $graphics.TextRenderingHint = [System.Drawing.Text.TextRenderingHint]::AntiAliasGridFit
      $graphics.FillPath($backgroundBrush, $path)

      $textFormat.Alignment = [System.Drawing.StringAlignment]::Center
      $textFormat.LineAlignment = [System.Drawing.StringAlignment]::Center
      $textBounds = [System.Drawing.RectangleF]::new(0, $size / 32, $size, $size)
      $graphics.DrawString($definition.Text, $font, $textBrush, $textBounds, $textFormat)

      $fileName = '{0}-{1}.png' -f $definition.Name, $size
      $outputPath = Join-Path $resolvedOutputDirectory $fileName
      $bitmap.Save($outputPath, [System.Drawing.Imaging.ImageFormat]::Png)
      $generatedIconData[$definition.Key][[string]$size] = Convert-BitmapToRgbaBase64 -Bitmap $bitmap
    }
    finally {
      $textFormat.Dispose()
      $font.Dispose()
      $textBrush.Dispose()
      $backgroundBrush.Dispose()
      $path.Dispose()
      $graphics.Dispose()
      $bitmap.Dispose()
    }
  }
}

$resolvedDataOutputPath = [System.IO.Path]::GetFullPath($DataOutputPath)
[System.IO.Directory]::CreateDirectory(
  [System.IO.Path]::GetDirectoryName($resolvedDataOutputPath)
) | Out-Null

$json = $generatedIconData | ConvertTo-Json -Depth 4 -Compress
$source = @"
// Generated by tools/generate-state-icons.ps1. Do not edit manually.
self.ProxySwitchIconData = Object.freeze($json);
"@
$utf8WithoutBom = [System.Text.UTF8Encoding]::new($false)
[System.IO.File]::WriteAllText($resolvedDataOutputPath, $source, $utf8WithoutBom)
